export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM'

export const CART_SAVE_SHIPPING_INFO = 'CART_SAVE_SHIPPING_INFO'
export const CART_SAVE_PAYMENT_INFO = 'CART_SAVE_PAYMENT_INFO'